export const imageMap = {

  "desk/desk-bunny.png": require("../assets/images/desk/desk-bunny.png"),
  "desk/Blue-desk-mini-comp.png": require("../assets/images/desk/Blue-desk-mini-comp.png"),
  "desk/Plain-solid.png": require("../assets/images/desk/Plain-solid.png"),
  "desk/Desk-radio.png": require("../assets/images/desk/Desk-radio.png"),
  "desk/White-frame-desk-photo.png": require("../assets/images/desk/White-frame-desk-photo.png"),
  "desk/purple-desk-mini-comp.png": require("../assets/images/desk/Purple-desk-mini-comp.png"),
  "desk/green-desk-mini-comp.png": require("../assets/images/desk/Green-desk-mini-comp.png"),
  "desk/Desk-flower-lamp.png": require("../assets/images/desk/Desk-flower-lamp.png"),
  "desk/Desk-wall-photos.png": require("../assets/images/desk/Desk-wall-photos.png"),
  "desk/desk-wallpaper-2.png": require("../assets/images/desk/desk-Wallpaper-2.png"),
  "desk/pink-desk-mini-comp.png": require("../assets/images/desk/Pink-desk-mini-comp.png"),
  "desk/desk-plant-peacelily.png": require("../assets/images/desk/desk-plant-peacelily.png"),
  "desk/desk-wallpaper-1.png": require("../assets/images/desk/Desk-wallpaper-1.png"),
  "desk/desk-plant-aglaonema.png": require("../assets/images/desk/desk-plant-aglaonema.png"),
  "desk/Desk-monstera.png": require("../assets/images/desk/Desk-monstera.png"),

  "bedroom/Br-checker-bed-pink.png": require("../assets/images/bedroom/Br-checker-bed-pink.png"),
  "bedroom/Br-checker-bed-blue.png": require("../assets/images/bedroom/Br-checker-bed-blue.png"),
  "bedroom/BR-floor-wood-grey.png": require("../assets/images/bedroom/BR-floor-wood-grey.png"),
  "bedroom/BR-floor-wood-medium.png": require("../assets/images/bedroom/BR-floor-wood-medium.png"),
  "bedroom/Bedroom-flower-photo.png": require("../assets/images/bedroom/Bedroom-flower-photo.png"),
  "bedroom/Bedroom-coffee-table.png": require("../assets/images/bedroom/Bedroom-coffee-table.png"),
  "bedroom/Bedroom-frilly-bed-red.png": require("../assets/images/bedroom/Bedroom-frilly-bed-red.png"),
  "bedroom/Br-checker-bed-orange.png": require("../assets/images/bedroom/Br-checker-bed-orange.png"),
  "bedroom/BR-floor-wood-dark.png": require("../assets/images/bedroom/BR-floor-wood-dark.png"),
  "bedroom/Bedroom-frilly-bed-green.png": require("../assets/images/bedroom/Bedroom-frilly-bed-green.png"),
  "bedroom/BR-floor-wood-light.png": require("../assets/images/bedroom/BR-floor-wood-light.png"),
  "bedroom/Bedroom-bookshelf.png": require("../assets/images/bedroom/Bedroom-bookshelf.png"),
  "bedroom/Bedroom-frilly-bed-pink.png": require("../assets/images/bedroom/Bedroom-frilly-bed-pink.png"),
  "bedroom/Bedroom-frilly-bed-blue.png": require("../assets/images/bedroom/Bedroom-frilly-bed-blue.png"),
  "bedroom/Br-checker-bed-green.png": require("../assets/images/bedroom/Br-checker-bed-green.png"),
  "bedroom/Bedroom-circle-rug.png": require("../assets/images/bedroom/Bedroom-circle-rug.png"),
  "bedroom/Bedroom-bow-photo.png": require("../assets/images/bedroom/Bedroom-bow-photo.png"),
  "bedroom/BR-bookshelf-plain.png": require("../assets/images/bedroom/BR-bookshelf-plain.png"),
  "bedroom/bookshelf-white.png": require("../assets/images/bedroom/bookshelf-white.png"),
  "bedroom/square-rug-darkblue.png": require("../assets/images/bedroom/square-rug-darkblue.png"),
  "bedroom/square-rug-orange.png": require("../assets/images/bedroom/square-rug-orange.png"),
  "bedroom/square-rug-lightblue.png": require("../assets/images/bedroom/square-rug-lightblue.png"),
  "bedroom/square-rug-green.png": require("../assets/images/bedroom/square-rug-green.png"),
  "bedroom/plain-bed.png": require("../assets/images/bedroom/plain-bed.png"),
  "bedroom/plain-table.png": require("../assets/images/bedroom/plain-table.png"),

};
